---
name: Checks
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: amitkr3007
          password: dckr_pat_Ceoyuv0WFm2hF3BJLy-Li_FtC08
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8 ."
